# Generated by Django 5.2.4 on 2025-07-26 17:44

import django.db.models.deletion
import products.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=500)),
                ('price', models.IntegerField()),
                ('count', models.IntegerField(default=0)),
                ('category', models.CharField(choices=[('Education', 'Education'), ('Electrics', 'Electrics'), ('Midecine', 'Medicine'), ('Fashion', 'Fashion'), ('Grocery', 'Grocery'), ('Kids', 'Kids'), ('Sport', 'Sport'), ('Beauty', 'Beauty'), ('Wearing', 'Wearing'), ('Religious', 'Religious')])),
                ('images', models.FileField(upload_to=products.models.products_image)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
