# Generated by Django 5.2.4 on 2025-07-29 12:47

import django.utils.timezone
import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=5000)),
                ('price', models.IntegerField()),
                ('measure', models.CharField(default='kg', max_length=50)),
                ('amount_sold', models.IntegerField(default=0)),
                ('category', models.CharField(choices=[('Education', 'Education'), ('Electrics', 'Electrics'), ('Midecine', 'Medicine'), ('Fashion', 'Fashion'), ('Grocery', 'Grocery'), ('Kids', 'Kids'), ('Sport', 'Sport'), ('Beauty', 'Beauty'), ('Wearing', 'Wearing'), ('Religious', 'Religious'), ('Fruits', 'Fruits'), ('Vegetables', 'Vegetables'), ('Household', 'Household'), ('Toys', 'Toys'), ('Pet', 'Pet'), ('Books', 'Books'), ('Stationary', 'Stationary'), ('Furniture', 'Furniture'), ('Tools', 'Tools'), ('Automotive', 'Automotive'), ('Garden', 'Garden')], max_length=50)),
                ('image', models.FileField(upload_to=products.models.products_image)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
