# Generated by Django 5.2.4 on 2025-07-26 17:58

import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='images',
            new_name='image',
        ),
        migrations.AddField(
            model_name='products',
            name='image1',
            field=models.FileField(blank=True, null=True, upload_to=products.models.products_image),
        ),
        migrations.AddField(
            model_name='products',
            name='image2',
            field=models.FileField(blank=True, null=True, upload_to=products.models.products_image),
        ),
        migrations.AddField(
            model_name='products',
            name='image3',
            field=models.FileField(blank=True, null=True, upload_to=products.models.products_image),
        ),
    ]
