# Generated by Django 5.2.4 on 2025-07-27 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_images_products_image_products_image1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='products',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='products',
            name='image3',
        ),
        migrations.AlterField(
            model_name='products',
            name='description',
            field=models.TextField(max_length=5000),
        ),
    ]
