# Generated by Django 5.2.4 on 2025-07-27 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_products_image1_remove_products_image2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('Education', 'Education'), ('Electrics', 'Electrics'), ('Midecine', 'Medicine'), ('Fashion', 'Fashion'), ('Grocery', 'Grocery'), ('Kids', 'Kids'), ('Sport', 'Sport'), ('Beauty', 'Beauty'), ('Wearing', 'Wearing'), ('Religious', 'Religious'), ('Fruits', 'Fruits'), ('Vegetables', 'Vegetables'), ('Household', 'Household'), ('Toys', 'Toys'), ('Pet', 'Pet'), ('Books', 'Books'), ('Stationary', 'Stationary'), ('Furniture', 'Furniture'), ('Tools', 'Tools'), ('Automotive', 'Automotive'), ('Garden', 'Garden')]),
        ),
    ]
